---
# roles/post/tasks/main.yml
- name: Adding sudo user
  import_tasks: sudouser.yml

- name: Add user ssh keys
  import_tasks: sshkeys.yml

- name: Dumpimg credentials locally
  import_tasks: creds.yml
