---
- name: Copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd
    mode: '0644'
  run_once: true
  delegate_to: localhost

- name: Writing gluster creds into file
  copy:
    dest: "/home/{{ username }}/.credentials"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
    content: |
      sudo username: {{ username }}
      sudo password: {{ password }}
  run_once: true
  delegate_to: localhost
