---
# roles/jitsi/tasks/repo.yml
- name: Download prosody GPG key
  get_url:
    url: https://prosody.im/files/prosody-debian-packages.key
    dest: /tmp/prosody.key
    mode: '0644'

- name: Dearmour prosody GPG key
  shell: gpg --dearmor < /tmp/prosody.key > /usr/share/keyrings/prosody-keyring.gpg

- name: Add prosody repository
  ansible.builtin.apt_repository:
    filename: prosody
    repo: 'deb [signed-by=/usr/share/keyrings/prosody-keyring.gpg] https://packages.prosody.im/debian noble main'

- name: Add jitsi GPG key
  get_url:
    url: https://download.jitsi.org/jitsi-key.gpg.key
    dest: /tmp/jitsi-key.gpg
    mode: '0644'

- name: Dearmouring jitsi key
  shell: gpg --dearmor < /tmp/jitsi-key.gpg > //usr/share/keyrings/jitsi-keyring.gpg

- name: Add jitsi repo
  ansible.builtin.apt_repository:
    filename: jitsi-stable
    repo: 'deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/'

- name: Apt update
  apt:
    update_cache: true
