---
- name: Apt update
  apt:
    update_cache: true

- name: Apt upgrade
  apt:
    upgrade: full

- name: Install basic packages
  apt:
    pkg:
      - net-tools
      - htop
      - rsync
      - fail2ban
      - ufw
      - software-properties-common
      - gnupg2
      - ssl-cert
      - openjdk-11-jdk
      - openjdk-11-jdk-headless
    state: present

- name: Fail2ban jail.local
  copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: true
    mode: '0644'
  notify: start fail2ban

- name: Secure ssh configs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.search }}"
    line: "{{ item.replace }}"
  loop:
    - { search: '^\#?PermitRootLogin (yes|no)', replace: 'PermitRootLogin without-password' }
    - { search: '^\#?PasswordAuthentication (yes|no)', replace: 'PasswordAuthentication no' }
    - { search: '^\#?PubkeyAuthentication (yes|no)', replace: 'PubkeyAuthentication yes' }
  notify: Restart ssh

- name: Apply ufw rules
  import_tasks: ufw_rules.yml
