---
- name: Download HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/GPG-KEY-hashicorp
    mode: '0644'

- name: Dearmor HashiCorp GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor --output /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/GPG-KEY-hashicorp
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp repo
  ansible.builtin.apt_repository:
    filename: hashicorp
    repo: >-
      deb [arch={{ ansible_architecture | replace("x86_64", "amd64") | replace("aarch64", "arm64") }}
      signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
      https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main

- name: Update repos
  apt:
    update_cache: true

- name: Creating consul data dir
  file:
    path: /opt/consul
    state: directory
    mode: '0755'

- name: Install consul package
  apt:
    name: consul
    state: present

- name: Move systemd service files
  ansible.builtin.copy:
    src: files/consul.service
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: '0664'
