---
- name: Install consul
  import_tasks: consul_install.yml

- name: Configure consul
  import_tasks: consul_config.yml

- name: Run consul
  import_tasks: consul_run.yml

- name: Bootstrap consul ACLs
  import_tasks: consul_bootstrap.yml
