---
- name: Update system packages
  import_role:
    name: update_pkgs

- name: Install basic packages
  apt:
    pkg:
      - htop
      - rsync
      - strace
      - figlet
      - software-properties-common
      - gnupg2
      - ssl-cert
      - python3-postgresql
      - python3-psycopg2
      - python3-passlib
    state: present

- name: Create sudo user
  import_role:
    name: sudouser
  run_once: true
  delegate_to: localhost

- name: Set root password
  import_role:
    name: setrootpwd

- name: Add SSH public keys
  import_role:
    name: sshkey
  run_once: true
  delegate_to: localhost

- name: Disable root login
  import_role:
    name: securessh
  when: disable_root is defined

- name: Enabling fail2ban
  import_role:
    name: fail2ban_install
