---
# vm configs
- name: Disable THP
  copy:
    src: 'files/disable-thp.service'
    dest: '/etc/systemd/system/disable-thp.service'
    mode: '0644'

- name: Reload and enable
  systemd:
    name: disable-thp.service
    state: started
    enabled: true
    daemon_reload: true

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present
    reload: true

- name: Configure hostname for cluster nodes
  hostname:
    use: systemd
    name: '{{ couchbase_data.server[count].instance.hostname }}'
  run_once: true
  delegate_to: '{{ item }}'
  loop: "{{ groups['couchbase_cluster'] }}"
  loop_control:
    index_var: count

- name: Update /etc/hosts on all of the nodes
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} couchbase servers"
    block: |
      #jinja2: trim_blocks:False
      # couchbase
      {%- for count in range(server_count | int) %}
      {{ couchbase_data.server[count].instance.ip_priv1 }} {{ couchbase_data.server[count].instance.hostname }}
      {%- endfor %}

- name: Update system packages
  import_role:
    name: update_pkgs

- name: Install basic packages
  apt:
    pkg:
      - net-tools
      - htop
      - rsync
      - software-properties-common
      - gnupg2
      - ssl-cert
      - python3-passlib
      - ufw
    state: present

# Set _domain variable
- name: Set _domain variable
  import_role:
    name: setdomain
  run_once: true
  delegate_to: localhost

# dns creation
- name: Create dns A record
  import_role:
    name: create_dns_record
  when: [token_password is defined, default_dns is not defined]
  run_once: true
  delegate_to: localhost

# disable root login w/wo pubkey
- name: Secure ssh
  import_role:
    name: securessh
  when: disable_root is defined

# ufw_install
- name: Enabling ufw
  import_role:
    name: ufw

# ufw rules
- name: Apply ufw rules
  import_tasks: ufw_rules.yml

# fail2ban
- name: Enabling fail2ban
  import_role:
    name: fail2ban_install
