---
# roles/common/tasks
- name: Configure hostnames for client nodes
  hostname:
    use: systemd
    name: '{{ nomad_data.client[count].instance.hostname }}'
  run_once: true
  delegate_to: '{{ item }}'
  loop: "{{ groups['nomad_client'] }}"
  loop_control:
    index_var: count

- name: Update /etc/hosts on all of the nodes
  blockinfile:
    path: /etc/hosts
    marker: '# {mark} nomad servers'
    block: |
      #jinja2: trim_blocks:False
      # nomad{%- for count in range(cluster_size) %}
      {{ nomad_data.client[count].instance.ip_priv1 }} {{ nomad_data.client[count].instance.hostname }}
      {%- endfor %}
  when:
    - cluster_mode == 'client'
    - is_provisioner == 'true'

# allows cluster play to use correct client var
- name: Update /etc/hosts on all of the nodes
  blockinfile:
    path: /etc/hosts
    marker: '# {mark} nomad servers'
    block: |
      #jinja2: trim_blocks:False
      # nomad{%- for count in range(clients) %}
      {{ nomad_data.client[count].instance.ip_priv1 }} {{ nomad_data.client[count].instance.hostname }}
      {%- endfor %}
  when: [cluster_mode == 'client', is_provisioner == 'false']

- name: Update system packages
  import_role:
    name: update_pkgs

- name: Install basic packages
  apt:
    pkg:
      - htop
      - rsync
      - software-properties-common
      - gnupg2
      - ssl-cert
      - python3-redis
      - python3-passlib
    state: present

- name: Configure firewalld
  import_tasks: firewall.yml

- name: Add docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Secure ssh
  import_role:
    name: securessh
  when: disable_root is defined
