---
- name: Copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Writing deployment credentials locally
  blockinfile:
    path: "/home/{{ username }}/.credentials"
    create: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    block: |
      # system user
      sudo username: {{ username }}
      sudo password: {{ password }}

      # spark user
      spark user: {{ spark_user }}
      spark ui password: {{ spark_ui_password }}
  delegate_to: localhost
  run_once: true
