---
- name: Installing Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: true
  when: inventory_hostname in groups['elasticsearch']

- name: Installing Logstash
  apt:
    name: logstash
    state: present
    update_cache: true
  when: inventory_hostname in groups['logstash']

- name: Installing Kibana
  apt:
    name: kibana
    state: present
    update_cache: true
  when: inventory_hostname in groups['provisioner']
