---
- name: Install basic packages
  apt:
    pkg: [apt-transport-https, net-tools]

- name: Download Elastic GPG key
  get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /tmp/GPG-KEY-elasticsearch
    mode: '0644'

- name: Add Elastic GPG key
  apt_key:
    file: /tmp/GPG-KEY-elasticsearch
    state: present

- name: Dearmoring signing key
  command:
    cmd: |
      gpg --dearmor --output
      /usr/share/keyrings/elasticsearch-keyring.gpg /tmp/GPG-KEY-elasticsearch

- name: Adding Elastic APT repo
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/9.x/apt stable main'
    filename: 'elastic-9.x'
    update_cache: true
    state: present
