---

# start service when cluster_mode is client
- name: Systemd daemon reload (client)
  systemd:
    daemon_reload: true
  when:
    - cluster_mode == 'client'
    - inventory_hostname in groups['nomad_client']

- name: Start and enable consul service (client)
  systemd:
    name: consul
    state: started
    enabled: true
  when:
    - cluster_mode == 'client'
    - inventory_hostname in groups['nomad_client']

# start service when cluster_mode is cluster
- name: Systemd daemon reload (cluster)
  systemd:
    daemon_reload: true
  when:
    - cluster_mode == 'cluster'
    - inventory_hostname in (groups['nomad_cluster'] | default([]))

- name: Start and enable consul service (cluster)
  systemd:
    name: consul
    state: started
    enabled: true
  when:
    - cluster_mode == 'cluster'
    - inventory_hostname in (groups['nomad_cluster'] | default([]))
