---
# roles/db/tasks/galera.yml

# set up galera1
- name: Set hostname {{ host1 }}
  hostname:
    name: '{{ host1 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

- name: Set facts for {{ host1 }}
  set_fact:
    wsrep_cluster_name: '{{ cluster_name }}'
    wsrep_node_address: '{{ priv_ip1 }}'
    wsrep_node_name: '{{ host1 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

- name: Configure galera.cnf {{ host1 }}
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: mysql
    group: mysql
    mode: '0640'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

# set up galera2
- name: Set hostname {{ host2 }}
  hostname:
    name: '{{ host2 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

- name: Set facts for {{ host2 }}
  set_fact:
    wsrep_cluster_name: '{{ cluster_name }}'
    wsrep_node_address: '{{ priv_ip2 }}'
    wsrep_node_name: '{{ host2 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

- name: Configure galera.cnf {{ host2 }}
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: mysql
    group: mysql
    mode: '0640'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

# set up galera3
- name: Set hostname {{ host3 }}
  hostname:
    name: '{{  host3 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"

- name: Set facts for {{ host3 }}
  set_fact:
    wsrep_cluster_name: '{{ cluster_name }}'
    wsrep_node_address: '{{ priv_ip3 }}'
    wsrep_node_name: '{{ host3 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"

- name: Configure galera.cnf {{ host3 }}
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: mysql
    group: mysql
    mode: '0640'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"
