---
# roles/common/tasks/domain.yml
- name: Set dns fact for subdomain
  set_fact:
    _domain: '{{ subdomain }}.{{ domain }}'
    cacheable: true
  when: [domain is defined, subdomain != "www"]

- name: Set dns fact for domain
  set_fact:
    _domain: '{{ domain }}'
    cacheable: true
  when: [domain is defined, subdomain == "www"]

- name: Set dns fact for default dns
  set_fact:
    _domain: '{{ default_dns }}'
    cacheable: true
  when: default_dns is defined
