---
- name: Update system packages
  import_role:
    name: update_pkgs

- name: Install basic packages
  apt:
    pkg:
      - ntp
      - gnupg2
      - wget
      - curl
      - htop
      - rsync
      - fail2ban
      - python3-pip
      - python3-pymysql
      - net-tools
      - apt-transport-https
      - ufw
    state: present

- name: Set _domain variable
  import_role:
    name: setdomain
  run_once: true
  delegate_to: localhost

- name: Create dns A record
  import_role:
    name: create_dns_record
  when:
    - token_password is defined
    - default_dns is not defined
  run_once: true
  delegate_to: localhost

- name: Create sudo user
  import_role:
    name: sudouser
  run_once: true
  delegate_to: localhost

- name: Set root password
  import_role:
    name: setrootpwd

- name: Add SSH public keys
  import_role:
    name: sshkey
  run_once: true
  delegate_to: localhost

- name: Disable root login
  import_role:
    name: securessh
  when: disable_root is defined

- name: Apply ufw rules
  import_tasks: ufw_rules.yml

- name: Enabling fail2ban
  import_role:
    name: fail2ban_install
