---
# roles/common/tasks

# common tasks for all instances
- name: Force ipv4 with apt
  copy:
    content: Acquire::ForceIPv4 "true";
    dest: /etc/apt/apt.conf.d/99force-ipv4
    mode: '0644'

- name: Apt update
  apt:
    update_cache: true

- name: Apt upgrade
  apt:
    upgrade: full

- name: Install basic packages
  apt:
    pkg:
      - ntp
      - wget
      - curl
      - htop
      - rsync
      - python3
      - python3-passlib
      - fail2ban
      - default-jdk
      - ufw
      - acl
    state: latest
  tags: test

- name: Fail2ban jail.local
  copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: true
    mode: '0644'
  notify: Start fail2ban

- name: Secure ssh configs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^\#?PermitRootLogin (yes|no)', line: 'PermitRootLogin without-password' }
    - { regexp: '^\#?PasswordAuthentication (yes|no)', line: 'PasswordAuthentication no' }
    - { regexp: '^\#?PubkeyAuthentication (yes|no)', line: 'PubkeyAuthentication yes' }
  notify: Restart ssh

- name: Apply ufw rules
  import_tasks: ufw_rules.yml
