---
- name: Writing deployment credentils locally
  blockinfile:
    path: '/home/{{ username }}/.deployment-secrets.txt'
    create: true
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: '0644'
    block: |
      # system user
      user: {{ username }}
      password: {{ password }}

      # cluster tag
      cluster_uuid: {{ cluster_uuid }}

      # hashi tokens
      consul_bootstrap_token: {{ consul_bootstrap_token[0] }}
      consul_nomad_autojoin_token: {{ consul_nomad_autojoin_token[0] }}
      nomad_bootstrap_token: {{ nomad_bootstrap_token[0] }}
      nomad_user_token: {{ nomad_user_token[0] }}
  run_once: true
  delegate_to: "{{ groups['nomad_cluster'][0] }}"
