---
- name: Restart firewalld
  systemd:
    name: firewalld
    state: restarted
    enabled: true

- name: Restart nomad
  systemd:
    name: nomad.service
    state: restarted
    enabled: true

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
