---

# start service on cluster when cluster_mode is cluster
- name: Systemd daemon reload
  systemd:
    daemon_reload: true
  delegate_to: '{{ item }}'
  loop: "{{ groups['nomad_client'] }}"
  when: cluster_mode == 'client'

- name: Start and enable nomad service
  systemd:
    name: nomad
    state: started
    enabled: true
  delegate_to: '{{ item }}'
  loop: "{{ groups['nomad_client'] }}"
  when: cluster_mode == 'client'

# start service on cluster when cluster_mode is cluster
- name: Systemd daemon reload
  systemd:
    daemon_reload: true
  delegate_to: '{{ item }}'
  loop: "{{ groups['nomad_cluster'] }}"
  when: cluster_mode == 'cluster'

- name: Start and enable nomad service
  systemd:
    name: nomad
    state: started
    enabled: true
  delegate_to: '{{ item }}'
  loop: "{{ groups['nomad_cluster'] }}"
  when: cluster_mode == 'cluster'
