---
- name: Create ELK cluster
  hosts: localhost
  any_errors_fatal: true
  vars_files: [group_vars/linode/vars]

  tasks:
    # Create credentials
    - name: Generating cluster passwords
      blockinfile:
        insertafter: EOF
        marker: "# {mark} ELK CREDS"
        path: group_vars/linode/vars
        block: |
          logstash_ingest_password: {{ lookup('password', '/dev/null length=45 chars=ascii_letters,digits') }}

  # Create instances
    - name: Creating Elasticsearch servers
      linode.cloud.instance:
        label: 'elasticsearch{{ item }}-{{ uuid }}'
        api_token: '{{ token_password }}'
        type: '{{ elasticsearch_cluster_type }}'
        region: '{{ region }}'
        image: '{{ image }}'
        disk_encryption: '{{ disk_encryption }}'
        root_pass: '{{ temp_root_pass }}'
        authorized_keys: '{{ provisioner_ssh_pubkey }}'
        private_ip: true
        # stackscript_id: 00000
        ua_prefix: 'cloud-marketplace-elk'
        tags: '{{ linode_tags }}'
        state: present
      with_sequence: count='{{ elasticsearch_cluster_size }}'

    - name: Get info about Elasticsearch servers
      linode.cloud.instance_info:
        api_token: '{{ token_password }}'
        label: 'elasticsearch{{ item }}-{{ uuid }}'
      register: elasticsearch_info
      with_sequence: count='{{ elasticsearch_cluster_size }}'

    - name: Creating Logstash servers
      linode.cloud.instance:
        label: 'logstash{{ item }}-{{ uuid }}'
        api_token: '{{ token_password }}'
        type: '{{ logstash_cluster_type }}'
        region: '{{ region }}'
        image: '{{ image }}'
        disk_encryption: '{{ disk_encryption }}'
        root_pass: '{{ temp_root_pass }}'
        authorized_keys: '{{ provisioner_ssh_pubkey }}'
        private_ip: true
        # stackscript_id: 00000
        ua_prefix: 'cloud-marketplace-elk'
        tags: '{{ linode_tags }}'
        state: present
      with_sequence: count='{{ logstash_cluster_size }}'

    - name: Get info about Logstash servers
      linode.cloud.instance_info:
        api_token: '{{ token_password }}'
        label: 'logstash{{ item }}-{{ uuid }}'
      register: logstash_info
      with_sequence: count='{{ logstash_cluster_size }}'

    - name: Get info about Kibana server
      linode.cloud.instance_info:
        api_token: '{{ token_password }}'
        label: '{{ provisioner }}'
      register: kibana_info
      with_sequence: count='{{ kibana_cluster_size }}'

    - name: Update group_vars
      blockinfile:
        path: ./group_vars/linode/vars
        marker: "# {mark} INSTANCE VARS"
        block: |
          #jinja2: trim_blocks:False
          data:
            elasticsearch:{%- for count in range(elasticsearch_cluster_size) %}
              - elasticsearch-{{ count + 1 }}:
                instance:
                  hostname: elasticsearch-{{ count + 1 }}.local
                  ip_pub1: {{ elasticsearch_info.results[count].instance.ipv4[0] }}
                  ip_priv1: {{ elasticsearch_info.results[count].instance.ipv4[1] }}
                  memory: {{ elasticsearch_info.results[count].instance.specs.memory }}
                  vpus: {{ elasticsearch_info.results[count].instance.specs.vcpus }}
          {%- endfor %}
            logstash:{%- for count in range(logstash_cluster_size) %}
              - logstash-{{ count + 1 }}:
                instance:
                  hostname: logstash-{{ count + 1 }}.local
                  ip_pub1: {{ logstash_info.results[count].instance.ipv4[0] }}
                  ip_priv1: {{ logstash_info.results[count].instance.ipv4[1] }}
                  memory: {{ logstash_info.results[count].instance.specs.memory }}
                  vpus: {{ logstash_info.results[count].instance.specs.vcpus }}
          {%- endfor %}
            kibana:{%- for count in range(kibana_cluster_size) %}
              - kibana-{{ count + 1 }}:
                instance:
                  hostname: kibana.local
                  ip_pub1: {{ kibana_info.results[count].instance.ipv4[0] }}
                  ip_priv1: {{ kibana_info.results[count].instance.ipv4[1] }}
                  memory: {{ kibana_info.results[count].instance.specs.memory }}
                  vpus: {{ kibana_info.results[count].instance.specs.vcpus }}
          {%- endfor %}

    - name: Add nodes to inventory
      blockinfile:
        path: ./hosts
        marker: "# {mark} ELK CLUSTER"
        block: |
          #jinja2: trim_blocks:False
          [provisioner]
          localhost ansible_connection=local user=root
          [elasticsearch]{%- for count in range(elasticsearch_cluster_size) %}
          {{ elasticsearch_info.results[count].instance.ipv4[0] }}
          {%- endfor %}
          [logstash]{%- for count in range(logstash_cluster_size) %}
          {{ logstash_info.results[count].instance.ipv4[0] }}
          {%- endfor %}
          [elk]
          localhost ansible_connection=local user=root{%- for count in range(elasticsearch_cluster_size) %}
          {{ elasticsearch_info.results[count].instance.ipv4[0] }}
          {%- endfor %}
          {%- for count in range(logstash_cluster_size) %}
          {{ logstash_info.results[count].instance.ipv4[0] }}
          {%- endfor %}

    - name: Wait for port 22 to become open
      wait_for:
        port: 22
        host: '{{ item.instance.ipv4[0] }}'
        search_regex: OpenSSH
        delay: 10
      connection: local
      with_items:
        - "{{ elasticsearch_info.results }}"
        - "{{ logstash_info.results }}"
